create table netology.CUSTOMERS
(
    id int generated by default as identify primary key,
    name varchar not null,
    surname varchar not null,
    age int not null,
    phone_number varchar not null
);

create table netology.ORDERS
(
    id int generated by default as identity primary key,
    date timestamp not null,
    customer_id int,
    product_name varchar not null,
    amount int not null,
    foreign key (customer_id) references netology.CUSTOMERS(id)
);

insert into netology.CUSTOMERS (name, surname, age, phone_number)
values ('Vadim', 'Volkov', 33, 89528880088);

insert into netology.CUSTOMERS (name, surname, age, phone_number)
values ('Danila', 'Volkov', 3, 89527770077);

insert into netology.CUSTOMERS (name, surname, age, phone_number)
values ('Olga', 'Volkova', 32, 89151180404);

insert into netology.ORDERS ("date", customer_id, product_name, amount)
values (current_date, 7, lexus, 1);

insert into netology.ORDERS ("date", customer_id, product_name, amount)
values (current_date, 6, bmw, 1);

insert into netology.ORDERS ("date", customer_id, product_name, amount)
values (current_date, 7, li, 1);

